
services:
    django:
        build: 
          context: .
          args:
            SECRET_KEY: ${SECRET_KEY}
            DEBUG: ${DEBUG}
        container_name: django
        #command: tail -f /dev/null
        env_file:
            - .env
        working_dir: /app/app  
        command: sh -c "gunicorn app.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
            - redis
        
        
    celery:
        build: 
          context: .
          args:
            SECRET_KEY: ${SECRET_KEY}
            DEBUG: ${DEBUG}
        env_file:
            - .env
        #command: tail -f /dev/null
        command: celery --app=app.celery worker --loglevel=info
        working_dir: /app/app  
        volumes:
            - .:/app
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres    
        container_name: pgdb
        env_file:
            - .env
        volumes:
             - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
volumes:
   pgdata: