# Generated by Django 5.2.2 on 2025-06-18 07:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rewardlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardrequestlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledreward',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RewardLog',
        ),
        migrations.DeleteModel(
            name='RewardRequestLog',
        ),
        migrations.DeleteModel(
            name='ScheduledReward',
        ),
    ]
